### PR TITLE
Added nmbd service

### PR DESCRIPTION
**Pull request by jfhenriques**
Added nmbd service to runit.
Was having issues in discovering the share in several places, for example in android I couldn't automatically discover shares in my network.

Probably a possible improvement will be to make the nmbd service only started by an environment variable check

### CODE REVIEW

**Comment by MarvAmBass** [comment]
Ohhh wow thank you, this might be the solution for a long open issue!

Didn't think about nmbd 😂 I thought it's more of an outdated compatibility layer

I'll take a look this evening and might merge right away 👍

**Comment by MarvAmBass** [comment]
merged it, thank you so much :)

**Comment by MarvAmBass** [comment]
congratulations, it seems you solved #91 with this merge - thanks!

**Comment by jfhenriques** [comment]
oh awesome. Glad It helped with #91# 😀

**Pull request merged**
