### PR TITLE
Allow MODEL to be used without a time machine share.

### PR DESCRIPTION
**Pull request by jameskr97**
Hi maintainers!

I noticed that when I was setting up this image on my NAS, my mac would not display the icon I selected unless I also created a Time Machine share. The `sed` update seen linked below did not make a change in the icon displayed. (This including when I restarted the mac in order to ensure there was no caching issue.)

https://github.com/ServerContainers/samba/blob/da091f302bf029ecec765a1591c6ba3352670e45/scripts/entrypoint.sh#L160-L161

I was able to fix this by moving the inclusion of the `_device-info._tcp` service block outside of the samba volume configuration.

Please let me know if any additional changes are desired before we can work on merging this PR.

### CODE REVIEW

**Comment by MarvAmBass** [comment]
Hi there, thanks for your work, I'll check the next days and maybe I merge it (first I need to make sure there is no negative impact on all those users)

**Comment by jameskr97** [comment]
@MarvAmBass Any chance of this getting looked at soon? I'm confident it won't affect any users using Time Machine, as the change only disassociates the txt record of the icon from the definition of the Time Machine.

**Comment by MarvAmBass** [comment]
I noticed a problem, that's why I didn't merge it by now 

I'm currently looking into it

**Comment by MarvAmBass** [comment]
okay it's implemented :)

**Pull request closed without merging**
